steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "jobs",
        "update",
        "sevenhunter-job",
        "--source=.",
        "--region=us-central1"
      ]

options:
  logging: CLOUD_LOGGING_ONLY
